package agent_test

import (
	"context"
	"errors"
	"iter"
	"sync/atomic"
	"testing"

	"github.com/bide-ai/bide/agent"
)

// sealingV is the PR's own sealing wrapper with Insert declared on the VALUE receiver. Passed by
// pointer (the usual way), (*sealingV).Insert is a compiler-generated wrapper whose file is
// "<autogenerated>", so declares() reports that the type does not declare Insert.
type sealingV struct {
	*agent.MemStore
	inserts *atomic.Int64
}

func (s sealingV) Insert(ctx context.Context, runID, name string, data []byte) (agent.Entry, bool, error) {
	s.inserts.Add(1)
	return s.MemStore.Insert(ctx, runID, name, data)
}

func TestEmbeddingWrapper_ValueReceiverByPointerNotRefused(t *testing.T) {
	ctx := context.Background()
	w := &sealingV{MemStore: agent.NewMemStore(), inserts: new(atomic.Int64)}
	_, err := agent.New(agent.NewScriptedModel(agent.TextTurn("done")), w).Run(ctx, "r", "hi")
	t.Logf("Run = %v; wrapper Inserts = %d", err, w.inserts.Load())
	if !errors.Is(err, agent.ErrConfig) && w.inserts.Load() == 0 {
		t.Fatal("wrapper not refused, and every write bypassed its Insert")
	}
}

// sealingG is the same wrapper as a generic type, pointer receiver.
type sealingG[T any] struct {
	*agent.MemStore
	inserts atomic.Int64
	_       T
}

func (s *sealingG[T]) Insert(ctx context.Context, runID, name string, data []byte) (agent.Entry, bool, error) {
	s.inserts.Add(1)
	return s.MemStore.Insert(ctx, runID, name, data)
}

func TestEmbeddingWrapper_GenericNotRefused(t *testing.T) {
	ctx := context.Background()
	w := &sealingG[int]{MemStore: agent.NewMemStore()}
	_, err := agent.New(agent.NewScriptedModel(agent.TextTurn("done")), w).Run(ctx, "r", "hi")
	t.Logf("Run = %v; wrapper Inserts = %d", err, w.inserts.Load())
	if !errors.Is(err, agent.ErrConfig) && w.inserts.Load() == 0 {
		t.Fatal("wrapper not refused, and every write bypassed its Insert")
	}
}

// sealingD embeds the Durable interface (a store handed around as a Durable) and declares the
// Store methods. It has no Journal() method, so checkDurable returns nil at its second test.
type sealingD struct {
	agent.Durable
	inner   *agent.MemStore
	inserts atomic.Int64
}

func (s *sealingD) Insert(ctx context.Context, runID, name string, data []byte) (agent.Entry, bool, error) {
	s.inserts.Add(1)
	return s.inner.Insert(ctx, runID, name, data)
}
func (s *sealingD) Get(ctx context.Context, r, n string) (agent.Entry, bool, error) {
	return s.inner.Get(ctx, r, n)
}
func (s *sealingD) Load(ctx context.Context, r string, a int64) iter.Seq2[agent.Entry, error] {
	return s.inner.Load(ctx, r, a)
}

func TestEmbeddingWrapper_DurableInterfaceNotRefused(t *testing.T) {
	ctx := context.Background()
	m := agent.NewMemStore()
	w := &sealingD{Durable: m, inner: m}
	_, err := agent.New(agent.NewScriptedModel(agent.TextTurn("done")), w).Run(ctx, "r", "hi")
	t.Logf("Run = %v; wrapper Inserts = %d", err, w.inserts.Load())
	if !errors.Is(err, agent.ErrConfig) && w.inserts.Load() == 0 {
		t.Fatal("wrapper not refused, and every write bypassed its Insert")
	}
}

// nested embeds the PR's sealing wrapper, declaring nothing itself: its Insert comes from
// sealing, its Do and History from the MemStore below it.
type nested struct{ *sealing }

func TestEmbeddingWrapper_NestedIsRefused(t *testing.T) {
	w := &nested{&sealing{MemStore: agent.NewMemStore()}}
	_, err := agent.New(agent.NewScriptedModel(agent.TextTurn("done")), w).Run(context.Background(), "r", "hi")
	if !errors.Is(err, agent.ErrConfig) {
		t.Fatalf("Run through a wrapper nesting a sealing wrapper = %v (Inserts %d); want ErrConfig", err, w.inserts.Load())
	}
}

// outerOfInterceptor embeds a wrapper that intercepts Do: it is driven through that Do.
type outerOfInterceptor struct{ *interceptsDo }

func TestEmbeddingWrapper_NestedInterceptorIsDrivenThroughItsDo(t *testing.T) {
	w := &outerOfInterceptor{&interceptsDo{MemStore: agent.NewMemStore()}}
	if _, err := agent.New(agent.NewScriptedModel(agent.TextTurn("done")), w).Run(context.Background(), "r", "hi"); err != nil {
		t.Fatal(err)
	}
	if w.dos.Load() == 0 {
		t.Fatal("the run bypassed the inner wrapper's Do")
	}
}

// Stores and the plain wrappers of the engine's tests are not refused.
func TestEmbeddingWrapper_PlainShapesAreAccepted(t *testing.T) {
	type countsRuns struct{ *agent.MemStore }
	for name, d := range map[string]agent.Durable{
		"MemStore":         agent.NewMemStore(),
		"embeds MemStore":  &countsRuns{agent.NewMemStore()},
		"embeds a Durable": struct{ agent.Durable }{agent.NewMemStore()},
	} {
		if _, err := agent.New(agent.NewScriptedModel(agent.TextTurn("done")), d).Run(context.Background(), "r", "hi"); err != nil {
			t.Errorf("%s: %v", name, err)
		}
	}
}
